### ISSUE TITLE
mysql-db does not initialize on init

### ISSUE THREAD

**Issue by anshumanrai** [HIIT/mydata-sdk#7]
on running sh start.sh inside mydata-sdk-master

I get the following lines

mysql-db  | MySQL init process in progress ...
mysql-db  | MySQL init process failed

mysql-db exited with code 1

Also all the services and celery workers start.

I am able to reach localhost:8080 and see the account creation page. When I try to create a page, I get an error saying the localhost did not send any response which I am guessing is because of no mysqld running in the back end.

Also the server side gives errors like cursor missing etc.

**Comment by Allu2** [comment]
I've failed to repeat the problem
Steps done:
1. clone repo https://github.com/HIIT/mydata-sdk
2. run: sh start.sh
Result:
3. MySQL and other services did start up as expected
I am also able to reach the account creation page in localhost:8080

Notes:
 The docker-compose.yml in the repo had old location for test service registry
Fixed by operator_components SERVICE_REGISTRY_SEARCH_DOMAIN value to working site
should look like this in the docker-compose.yml
      - SERVICE_REGISTRY_SEARCH_DOMAIN='http://node.registry.sandbox.mydata.fi'

**Comment by anshumanrai** [comment]
Does this need mysql-server and mysql-client packages installed on ubuntu. I installed these packages just now but I still get the same issue.

**Comment by anshumanrai** [comment]
Also I guess I need to specify the root password for the root account of mysql. 

Do I need to create a user called mydataaccount as in the docker-compose.yml file or does it get created automatically.

**Comment by Allu2** [comment]
As per the [README.md](https://github.com/HIIT/mydata-sdk#simple-consent-flow-demo
)
All you need is Docker, Docker-compose and few python dependencies (for the ui_flow.py)

> Does this need mysql-server and mysql-client packages installed on ubuntu.

No, the docker container for mysql is provided by the docker-compose.yml and configured so that every other module using the mysql-db is also using the said configuration, You can run local mysql installation(or even remote) but in this case you need to configure each other module appropriately to use this local instance.

> Also I guess I need to specify the root password for the root account of mysql.

No, the docker container with mysql-db will be automatically configured.

The docker setup will have mysql container readily set up and configured for you. For the test purposes you don't need to do anything more to get the stack running (besides running the start.sh with docker and docker-compose installed)
If you want to try the test flow you need to apply the the fix I mentioned earlier into the docker-compose.yml and have the required python dependencies that ui_flow.py uses (mainly Python Requests)

If you are still having trouble getting the stack to work with the start.sh I'd request you to:

1. Clean up old containers from your docker.
2. Make a new folder and follow the steps README.md for simple-consent-flow-demo.
3. Store logs of output from each command and the start.sh once the setup is running.

If the same problem occurs copy the logs and paste them into some pastebin or here so we can take a look at them in more detail, also include your docker and docker-compose versions

**Comment by anshumanrai** [comment]
I still have issues after cleaning up the docker and starting with a new folder. I am attaching the output logs and error logs.
[out.txt](https://github.com/HIIT/mydata-sdk/files/1107347/out.txt)
[err.txt](https://github.com/HIIT/mydata-sdk/files/1107348/err.txt)

**Comment by anshumanrai** [comment]
I forgot to mention docker version 17.03.1-ce build c6d412e

docker-compose version 1.14.0 build c7bdf9e

**Comment by anshumanrai** [comment]
Are you guys sure you are using the latest version. May be this problem shows up with the latest version. Do you recommend that I try a lower version. Also just to tell you I am using virtualbox as an environment.

**Comment by anshumanrai** [comment]
I mean the latest version mydata-sdk

**Comment by anshumanrai** [comment]
I confirmed that this is an issue with the latest release on master. v 1.2.1 is ok.
